[Test Configuration]
Test Configuration.<size(s)> = "5"
Test Configuration 0.Script Name = "Start Module"
Test Configuration 0.INI File Path = "UserFiles-PMU\\Plugins\\FGen\\NiPxi6733\\PMU_Cal.ini"
Test Configuration 1.Script Name = "Start Module"
Test Configuration 1.INI File Path = "UserFiles-PMU\\Plugins\\Digitizer\\NiDaqMx\\PMU_Cal.ini"
Test Configuration 2.Script Name = "Start Module"
Test Configuration 2.INI File Path = "UserFiles-PMU\\Plugins\\Sensor\\C37.118 PMU\\C37.118_PMU.ini"
Test Configuration 3.Script Name = "Start Module"
Test Configuration 3.INI File Path = "UserFiles-PMU\\Plugins\\Analysis\\PmuAnalysis\\PMU (Ramp).ini"
Test Configuration 4.Script Name = "Start Module"
Test Configuration 4.INI File Path = "UserFiles-PMU\\Plugins\\Sync\\PXI_MultiTrig\\Dyn3_PMUCal.ini"